version: '3.5'

services:

  mysql:
    image: mysql
    container_name: mysql_mediscreen
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: smashed31
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

    ports:
      - 3307:3306
    volumes:
      - mysql_db:/data/db

  mongodb:
    image: mongo:latest
    container_name: mongodb_mediscreen
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      -   27018:27017
    volumes:
      -   mongodb_db:/data/db

#  mspatient:
#    build: ./Mediscreen-ms-patient
#    network_mode: host
#    image: ms-patient:latest
#    depends_on:
#      mysql:
#        condition: service_healthy
volumes:
  mongodb_db:
  mysql_db: